// File generated by Firebase MCP — do not edit manually.
// firebase-dart-plugin version 3.x / FlutterFire

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBXnmrRMEeoTS-2VH5PSHftIt7q7vTdsE',
    appId: '1:541133398477:android:b2a5fbedbc3bcdf6d66484',
    messagingSenderId: '541133398477',
    projectId: 'lust-meter-app-01',
    storageBucket: 'lust-meter-app-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrO21FzPcSThZgo3JTF1RVGN6AQBAO4IM',
    appId: '1:541133398477:ios:eca6237f7b5cf28dd66484',
    messagingSenderId: '541133398477',
    projectId: 'lust-meter-app-01',
    storageBucket: 'lust-meter-app-01.firebasestorage.app',
    iosBundleId: 'com.lustmeter.app',
  );

  // Web config (can be filled if web platform is added later)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBXnmrRMEeoTS-2VH5PSHftIt7q7vTdsE',
    appId: '1:541133398477:web:placeholder',
    messagingSenderId: '541133398477',
    projectId: 'lust-meter-app-01',
    storageBucket: 'lust-meter-app-01.firebasestorage.app',
    authDomain: 'lust-meter-app-01.firebaseapp.com',
  );
}
